### ISSUE TITLE
Which configuration of CESM?

### ISSUE THREAD

**Issue by dorchard** [m2lines/convection-parameterization-in-CAM#4]
- [x] Which version of CESM should we be trying to put this into? [CESM 2.2 is the latest stable release](https://escomp.github.io/CESM/versions/cesm2.2/html/downloading_cesm.html)

We know we want to be running CESM in "aquaplanet" mode. Looking at the [quick start guide](https://escomp.github.io/CESM/versions/cesm2.2/html/quickstart.html) we configure CESM via the `create_newcase` tool. Which then leads to questions:

- [ ] Which component set definitions should we use (see https://www2.cesm.ucar.edu/models/cesm2/config/compsets.html) for aquaplanet mode. There are 18 component sets when searching here for "aquaplanet"
- [ ] Which grid resolution?

- [ ] Which input data should we use (can we use something smaller and coarser?)

**Comment by jatkinson1000** [comment]
Potentially useful in future so making a note here: It is possible to run SAM using SCAM input files in the latest version should we wish to do a direct comparison.

**Comment by jatkinson1000** [comment]
I am re-opening this issue as the move to Derecho has raised some problems.

On Cheyenne we used CESM version 2.1.0, but this is not building on Derecho (due to python issues I think).
I have successfully built v2.1.5 and v2.2, but when I try and build using the SourceMods I updated for v2.1.0 it no longer works, and a diff shows substantial differences in the source.

Before I get too far ahead do you have any recommendations for the version to work with on Derecho going forward @paogorman @judithberner ?
Assuming the ZM/deep convection hasn't changed my feeling is to use v2.2.0 as reasonably recent?

**Comment by jatkinson1000** [comment]
Digging a bit deeper it seems the issue occurs in any version of CESM, as I think it always checks out the most recent version of CAM (currently `cam_cesm2_1_rel_41`), which is where these conflicting changes occur.

As a result I will proceed with updating our modifications for this version of CAM if that seems reasonable?

**Comment by jatkinson1000** [comment]
Closing this as the version of CESM and the CAM tag on which our fork is based off of is now included in the documentation, along with a note about potential future changes to CAM/CESM.
